export { plugin as ApiDocs } from '@backstage/plugin-api-docs';
export { catalogPlugin as CatalogPlugin } from '@backstage/plugin-catalog';
export { plugin as TechRadar } from '@backstage/plugin-tech-radar';
export { plugin as GithubActions } from '@backstage/plugin-github-actions';
export { plugin as CostInsights } from '@backstage/plugin-cost-insights';
export { plugin as GraphiQL } from '@backstage/plugin-graphiql';
export { plugin as UserSettings } from '@backstage/plugin-user-settings';
export { plugin as TechDocs } from '@backstage/plugin-techdocs';
export { badgesPlugin } from '@backstage/plugin-badges';
export { todoPlugin } from '@backstage/plugin-todo';
