compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - checksum: 715dda5d3b377cb2c52ba1d6901a98585401f44794445e98c8f3a46224c85b8ee04b8d4648a8e8c9a7a7d9318005678f98830c066bc4f062dbcf08b63a0f8927
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: 'https://versions.backstage.io/v1/releases/1.49.0-next.0/yarn-plugin'

yarnPath: .yarn/releases/yarn-4.5.0.cjs
