compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - checksum: ed8eb542bb8100843e62f9061d04e06cab181c8d1116a145a927fd70faf6dcba2f970eec18909579a922ec28dc1e3448b607e9af1cce5a54885d0cde70bf90ca
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: 'https://versions.backstage.io/v1/releases/1.46.0-next.0/yarn-plugin'

yarnPath: .yarn/releases/yarn-4.5.0.cjs
