compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - checksum: 8fa2e3a1cdf5076dde96b177618478419daea000b8038412817583e4d309fd39bf4813a337eb1fad3bfe9036d31732f7416383affbe3d420f48eacb60f6184d5
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: 'https://versions.backstage.io/v1/tags/main/yarn-plugin'

yarnPath: .yarn/releases/yarn-4.5.0.cjs
