compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - checksum: 7cc0db5bb02d9e008b2146be22fdf157e38e0ae5cb9f37e715b0be3ab6133554fc83d65eebda724c033a05583976f78a802a50c1a17db8fb0a9b115ec1870a52
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: 'https://versions.backstage.io/v1/releases/1.49.0-next.1/yarn-plugin'

yarnPath: .yarn/releases/yarn-4.5.0.cjs
