compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - checksum: 2eda215600fa289952383d999f87e6fa46a333fd737a8a221a1e2326d4c95a2d694510b5e6aa5a3ef5b8927b48ce7ea1d5783efc4be18d5f87cf57d5fa16b966
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: 'https://versions.backstage.io/v1/releases/1.39.0-next.0/yarn-plugin'

yarnPath: .yarn/releases/yarn-4.5.0.cjs
