compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - checksum: 11dfd309345f75c4a3cc224b0a76d11d501f3ecce75084f94da5191429daf43c223eefc35490e67a8e18c5f9f5fe3c53d462fba5ff374b846edd1a84ed10b181
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: 'https://versions.backstage.io/v1/tags/next/yarn-plugin'

yarnPath: .yarn/releases/yarn-4.5.0.cjs
