compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - checksum: f80ae33558c6fb60bf74f58f8f6ceab7e441e9e5c3b84b4d49b41437c35e6975aae9616f5a0015c3d79696ac7faf74c7d57a6d66b849012265fa68146e06fed0
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: 'https://versions.backstage.io/v1/releases/1.50.0-next.2/yarn-plugin'

yarnPath: .yarn/releases/yarn-4.5.0.cjs
