apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-demo
  description: An example component showcasing GitHub Actions workflows.
  annotations:
    # **GitHub repository identifier**; used by the GitHub Actions plugin to locate your repo.
    github.com/project-slug: backstage/demo
    # Optionally, add the managed-by-location annotation to point to your GitHub repo.
    backstage.io/managed-by-location: url:https://github.com/backstage/demo?ref=main
spec:
  type: service
  owner: backstage/maintainers
  lifecycle: experimental
