# Helpful links:
# http://localhost:9464/metrics - Backstage metrics
# http://localhost:9090 - Prometheus
# http://localhost:3001 - Grafana
# http://localhost:16686 - Jaeger

version: '3'
services:
  prometheus:
    image: prom/prometheus@sha256:9abc6cf6aea7710d163dbb28d8eeb7dc5baef01e38fa4cd146a406dd9f07f70d
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana@sha256:b5b59bfc7561634c2d7b136c4543d702ebcc94a3da477f21ff26f89ffd4214fa
    ports:
      - 3001:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/backstage.json
    volumes:
      - ./dashboards/:/etc/grafana/provisioning/dashboards/
      - ./datasources/:/etc/grafana/provisioning/datasources/
    networks:
      - monitoring

  jaeger:
    image: jaegertracing/all-in-one:latest@sha256:c73bec5e6220b91eeda2574ec6aabbb8232f531e6b0bd11819f53548eefa6424
    networks:
      - monitoring
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=:9411
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 9411:9411

networks:
  monitoring:
    external: true
