{
 "title": "Backstage OpenTelemetry Showcase",
 "description": "This is a showcase of the various metrics provided by Backstage along with auto instrumented metrics to help setup observability for your Backstage instance!",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Catalog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Catalog Processing Queue Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(rate(catalog_processing_queue_delay_sum{}[1m]) / rate(catalog_processing_queue_delay_count{}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catalog Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "max(rate(catalog_processing_duration_sum{}[1m]) / rate(catalog_processing_duration_count{}[1m])) by (result)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catalog Processed Entities Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(irate(catalog_processed_entities_count_total{}[5m])) by(result)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catalog Stitching Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(catalog_stitching_queue_length{}) by(instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catalog Entities Stitched Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(irate(catalog_stitched_entities_count_total{}[5m])) by(result)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catalog Stitching Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "max(rate(catalog_stitching_duration_sum{}[1m]) / rate(catalog_stitching_duration_count{}[1m])) by (result)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catalog Entities Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max(catalog_entities_count{}) by(kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Backend Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Backend Tasks Time Since Scheduler Task Start",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "time() - (max(backend_tasks_task_runs_started{}) by (instance, taskId))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Tasks Runs Started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "max(backend_tasks_task_runs_started) by(taskId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Tasks Runs Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "max(backend_tasks_task_runs_completed) by(taskId)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Scaffolder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Scaffolder Step Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "max(scaffolder_step_count_total{}) by (template, step)",
     "legendFormat": "{{template}} - {{step}}"
    }
   ]
  },
  {
   "title": "Scaffolder Task Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "max(scaffolder_task_count_total{}) by (template)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}